function create(vObj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
% Abstract: This function creates all parts of the viewer display
%
% Syntax:
%           create(vObj)
%
% Inputs:
%           vObj - The PKPDViewer.Fitting vObject
%
% Outputs:
%           none
%
% Examples:
%           none
%
% Notes: none
%

% Copyright 2017 The MathWorks, Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: agajjala $
%   $Revision: 420 $  $Date: 2017-12-07 14:47:44 -0500 (Thu, 07 Dec 2017) $
% ---------------------------------------------------------------------

% Main vertical layout
vObj.h.MainLayout = uix.VBox(...
    'Parent',vObj.hPanel,...
    'Padding',5,...
    'Spacing',5);
% Dose - Target Species Mapping
vObj.h.DoseMappingLayout = uix.HBox(...
    'Parent',vObj.h.MainLayout);
% Concentration - Target Species Mapping
vObj.h.ConcMappingLayout = uix.HBox(...
    'Parent',vObj.h.MainLayout);
% Pooled Fitting
vObj.h.PooledFittingLayout = uix.HBox(...
    'Parent',vObj.h.MainLayout);
% Error Model
vObj.h.ErrorModelLayout = uix.HBox(...
    'Parent',vObj.h.MainLayout);
% Parameters
vObj.h.ParametersPanel = uix.Panel(...
    'Parent',vObj.h.MainLayout,...
    'BorderType','none',...
    'Title','Parameters:',...
    'FontWeight','bold',...
    'FontSize',10);
% Set sizes
vObj.h.MainLayout.Heights = [70 70 30 30 300];


%% Concentration - Target Species Mapping

vObj.h.DoseMappingLabel = uicontrol(...
    'Parent',vObj.h.DoseMappingLayout,...
    'Style','text',...
    'String',sprintf('Dose\nMapping:'),...
    'FontWeight','bold',...
    'TooltipString','Dose - Target Species Mapping for Fitting',...
    'HorizontalAlignment','left',...
    'FontSize',10);
if vObj.IsPC
    vObj.h.DoseMappingTable = uiextras.jTable.Table(...
        'Parent',vObj.h.DoseMappingLayout,...
        'ColumnName',{'Dose','Target Species'},...
        'ColumnFormat',{'char','popup'},...
        'ColumnEditable',[false true],...
        'ColumnMinWidth',[50 50],...
        'ColumnWidth',[75 100],...
        'Data',{},...
        'Tag','DoseMappingTable',...
        'CellEditCallback',@(h,e)onDoseSpeciesTableEdited(vObj,h,e));
    % Automatically size to fit contents
    vObj.h.DoseMappingTable.ColumnResizePolicy = 'off';
    vObj.h.DoseMappingTable.sizeColumnsToData();
else
    vObj.h.DoseMappingTable = uitable(...
        'Parent',vObj.h.DoseMappingLayout,...
        'RowName',{},...
        'ColumnName',{'Dose','Target Species'},...
        'ColumnEditable',[false true],...
        ...'ColumnMinWidth',[50 50],...
        ...'ColumnWidth',[75 100],...
        'Data',{},...
        'Tag','DoseMappingTable',...
        'CellEditCallback',@(h,e)onDoseSpeciesTableEdited(vObj,h,e));
end

vObj.h.DoseMappingLayout.Widths = [60 -1];


%% Concentration - Target Species Mapping

vObj.h.ConcMappingLabel = uicontrol(...
    'Parent',vObj.h.ConcMappingLayout,...
    'Style','text',...
    'String',sprintf('Species\nMapping:'),...
    'FontWeight','bold',...
    'TooltipString','Species - Target Species Mapping for Fitting',...
    'HorizontalAlignment','left',...
    'FontSize',10);
if vObj.IsPC
    vObj.h.ConcMappingTable = uiextras.jTable.Table(...
        'Parent',vObj.h.ConcMappingLayout,...
        'ColumnName',{'Dependent','Target Species'},...
        'ColumnFormat',{'char','popup'},...
        'ColumnEditable',[false true],...
        'ColumnMinWidth',[50 50],...
        'ColumnWidth',[75 100],...
        'Data',{},...
        'Tag','ConcMappingTable',...
        'CellEditCallback',@(h,e)onConcSpeciesTableEdited(vObj,h,e));
    % Automatically size to fit contents
    vObj.h.ConcMappingTable.ColumnResizePolicy = 'off';
    vObj.h.ConcMappingTable.sizeColumnsToData();
else
    vObj.h.ConcMappingTable = uitable(...
        'Parent',vObj.h.ConcMappingLayout,...
        'RowName',{},...
        'ColumnName',{'Dependent','Target Species'},...
        ...'ColumnFormat',{'char','popup'},...
        'ColumnEditable',[false true],...
        ...'ColumnMinWidth',[50 50],...
        ...'ColumnWidth',[75 100],...
        'Data',{},...
        'Tag','ConcMappingTable',...
        'CellEditCallback',@(h,e)onConcSpeciesTableEdited(vObj,h,e));
end

vObj.h.ConcMappingLayout.Widths = [60 -1];


%% Pooled Fitting

% Overlay checkbox
vObj.h.PooledFittingCheckbox = uicontrol(...
    'Parent',vObj.h.PooledFittingLayout,...
    'Style','checkbox',...
    'String','Pooled Fitting',...
    'Value',0,...    
    'Tag','PooledFittingCheckbox',...
    'HorizontalAlignment','left',...
    'FontWeight','bold',...
    'FontSize',10,...
    'Callback',@(h,e)onSelectPooledFitting(vObj,h,e));


%% Error Model

vObj.h.FitErrorModelLabel = uicontrol(...
    'Parent',vObj.h.ErrorModelLayout,...
    'Style','text',...
    'String','Error:',...
    'TooltipString','Fitting Error Model',...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontSize',10);
vObj.h.FitErrorModelPopup = uicontrol(...
    'Parent',vObj.h.ErrorModelLayout,...
    'Style','popup',...
    'String',PKPD.Analysis.FitErrorModelOptions,...
    'Value',1,...
    'TooltipString','Fitting Error Model',...
    'Tag','ErrorModelPopup',...
    'HorizontalAlignment','left',...
    'FontSize',8,...
    'Callback',@(h,e)onSelectErrorModel(vObj,h,e));
vObj.h.ErrorModelLayout.Widths = [60 -1];


%% Parameters

vObj.h.ParametersLayout = uix.VBox(...
    'Parent',vObj.h.ParametersPanel);

% Button layout
vObj.h.ParametersButtonLayout = uix.HBox(...
    'Parent',vObj.h.ParametersLayout,...
    'Spacing',5);
uix.Empty('Parent',vObj.h.ParametersButtonLayout);
Icon = UIUtilities.iconRead(fullfile(matlabroot, '/toolbox/matlab/icons/redo.mat'));
vObj.h.RestoreDefaultsButton = uicontrol(...
    'Style','pushbutton',...
    'CData',Icon,...
    'TooltipString','Reset to defaults...',...
    'Parent',vObj.h.ParametersButtonLayout,...
    'Callback',@(h,e)onRestoreDefaults(vObj,h,e));
Icon = UIUtilities.iconRead(fullfile(matlabroot, '/toolbox/matlab/icons/file_save.png'));
vObj.h.SaveAsVariantButton = uicontrol(...
    'Style','pushbutton',...
    'CData',Icon,...
    'TooltipString','Save as variant...',...
    'Parent',vObj.h.ParametersButtonLayout,...
    'Callback',@(h,e)onSaveAsVariant(vObj,h,e));
vObj.h.ParametersButtonLayout.Widths = [-1 30 30];

if vObj.IsPC
    vObj.h.ParametersTable = uiextras.jTable.Table(...
        'Parent',vObj.h.ParametersLayout,...
        'ColumnName',{'Name','Fit?','Initial','FitValue','Units','Min','Max'},...
        'ColumnFormat',{'char','boolean','float','char','char','float','float'},...
        'ColumnEditable',[false true true false false true true],...
        'ColumnMinWidth',[100 50 75 150 75 75 75],...
        'Data',{},...
        'Tag','ParametersTable',...
        'CellEditCallback',@(h,e)onParamsTableEdited(vObj,h,e));
    % Automatically size to fit contents
    vObj.h.ParametersTable.ColumnResizePolicy = 'off';
    vObj.h.ParametersTable.sizeColumnsToData();    
else
    vObj.h.ParametersTable = uitable(...
        'Parent',vObj.h.ParametersLayout,...
        'RowName',{},...
        'ColumnName',{'Name','Fit?','Initial','FitValue','Units','Min','Max'},...
        'ColumnFormat',{'char','logical','numeric','char','char','numeric','numeric'},...
        'ColumnEditable',[false true true false false true true],...
        ...'ColumnMinWidth',[100 50 75 150 75 75 75],...
        'Data',{},...
        'Tag','ParametersTable',...
        'CellEditCallback',@(h,e)onParamsTableEdited(vObj,h,e));
end

vObj.h.ParametersLayout.Heights = [30 250];
