function create(vObj)
% create - Creates all parts of the viewer display
% -------------------------------------------------------------------------
% Abstract: This function creates all parts of the viewer display
%
% Syntax:
%           create(vObj)
%
% Inputs:
%           vObj - The PKPDViewer.Simulation vObject
%
% Outputs:
%           none
%
% Examples:
%           none
%
% Notes: none
%

% Copyright 2017 The MathWorks, Inc.
%
% Auth/Revision:
%   MathWorks Consulting
%   $Author: agajjala $
%   $Revision: 420 $  $Date: 2017-12-07 14:47:44 -0500 (Thu, 07 Dec 2017) $
% ---------------------------------------------------------------------

% Main vertical layout
vObj.h.MainLayout = uix.VBox(...
    'Parent',vObj.hPanel,...
    'Padding',5,...
    'Spacing',8);
% Time
vObj.h.TimeLayout = uix.HBox(...
    'Parent',vObj.h.MainLayout,...
    'Spacing',5);
% Number Of Runs
vObj.h.NumberOfRunsLayout = uix.HBox(...
    'Parent',vObj.h.MainLayout,...
    'Padding',2,...
    'Spacing',5);
% Parameters
vObj.h.ParametersPanel = uix.Panel(...
    'Parent',vObj.h.MainLayout,...
    'BorderType','none',...
    'Title','Parameters:',...
    'FontWeight','bold',...
    'FontSize',10);
% Set sizes - NOTE: Parameters panel will be sized according to # of
% parameters
vObj.h.MainLayout.Heights = [25 25 500];


%% Time

vObj.h.TimeNameLabel = uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','text',...
    'String','Time:',...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontSize',10);
vObj.h.TimeStartEdit = uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','edit',...
    'String','',...
    'HorizontalAlignment','left',...
    'TooltipString','Simulation Start Time',...
    'Tag','StartTime',...
    'FontSize',10,...
    'Callback',@(h,e)onEdit(vObj,h,e));
uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','text',...
    'String',':',...
    'HorizontalAlignment','center',...
    'FontSize',10);
vObj.h.TimeStepEdit = uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','edit',...
    'String','',...
    'HorizontalAlignment','left',...
    'TooltipString','Simulation Output TimeStep',...
    'Tag','TimeStep',...
    'FontSize',10,...
    'Callback',@(h,e)onEdit(vObj,h,e));
uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','text',...
    'String',':',...
    'HorizontalAlignment','center',...
    'FontSize',10);
vObj.h.TimeStopEdit = uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','edit',...
    'String','',...
    'HorizontalAlignment','left',...
    'TooltipString','Simulation Stop Time',...
    'Tag','StopTime',...
    'FontSize',10,...
    'Callback',@(h,e)onEdit(vObj,h,e));
vObj.h.TimeUnitsLabel = uicontrol(...
    'Parent',vObj.h.TimeLayout,...
    'Style','text',...
    'String','units',...
    'TooltipString','Time Units',...
    'HorizontalAlignment','left',...
    'FontSize',10);
vObj.h.TimeLayout.Widths = [60 -1 5 -1 5 -1 -1];

%% Number of Runs (Population only)

vObj.h.NumberOfRunsLabel = uicontrol(...
    'Parent',vObj.h.NumberOfRunsLayout,...
    'Style','text',...
    'String','No. of Simulations:',...
    'FontWeight','bold',...
    'HorizontalAlignment','left',...
    'FontSize',10);
vObj.h.NumberOfRunsEdit = uicontrol(...
    'Parent',vObj.h.NumberOfRunsLayout,...
    'Style','edit',...
    'String','',...
    'HorizontalAlignment','left',...
    'TooltipString','Number of population simulations',...
    'Tag','NumPopulationRuns',...
    'FontSize',10,...
    'Callback',@(h,e)onEdit(vObj,h,e));

vObj.h.NumberOfRunsLayout.Widths = [120 -1];

%% Parameters

[ParamLayoutHeight,NumParams] = createParametersLayout(vObj); %#ok<ASGLU>

% % Update sizes
% Buffer = NumParams*10; 
% vObj.h.MainLayout.Heights(end) = ParamLayoutHeight + Buffer; % Add some buffer



